apiVersion: v1
kind: Secret
metadata:
  name: secrets-ens-api-qa   # Name of the secret
  namespace: acoe-qa-env-apps # acoedev-k8s15n-dev     # Namespace where the secret will be created
type: Opaque
data:
  AZURE_ENDPOINT: aHR0cHM6Ly9zd2Nkb2FpMngyYW9hMDEub3BlbmFpLmF6dXJlLmNvbS8=          # Base64-encoded value for "api-key"
  API_KEY: Y2I0YjFhMDMxMTQ1NDE5OGFkNGM5YzQyZTljNGU1ZDc=   # Base64-encoded value for "api-secret"
  CONFIG: REVNTw==    # Base64-encoded value for "db-username"
  SCRAPER: aHR0cDovLzEyNy4wLjAuMTozMDAx #dnhMUDBpQ2tjZUZvUG82Nnh4dFpJdjlUclY0dm5oQnpwcE1CcDNjV1NDZw==       # Base64-encoded value for "db-password"
  #bmVvNGorc3NjOi8vNGEzM2U3ODMuZGF0YWJhc2VzLm5lbzRqLmlv